### ISSUE TITLE
Code improvement suggestions

### ISSUE THREAD

**Issue by y9san9** [kotleni/PomodoroProject-android#1]
1. Packages `adapters`, `fragments`, `repositories`, `repos` are inconvenient. It's better to group classes not by their direct purpose but rather by their features. For example you could create `newTask`, `tasks` `settings` packages, so you won't have cluttered package with hundreds of viewmodels.

2. https://github.com/kotleni/PomodoroProject-android/blob/9204a862e0e650b66ae581e8914d05f8141ac69b/app/src/main/java/kotleni/pomodoro/adapters/TasksAdapter.kt#L48-L57
    Why so? You have [this](https://github.com/kotleni/PomodoroProject-android/blob/9204a862e0e650b66ae581e8914d05f8141ac69b/app/src/main/java/kotleni/pomodoro/OnItemTaskListener.kt) interface already

3. You have an architecture problem with Fragment and viewmodel responsibilities

    1. https://github.com/kotleni/PomodoroProject-android/blob/9204a862e0e650b66ae581e8914d05f8141ac69b/app/src/main/java/kotleni/pomodoro/fragments/NewTaskFragment.kt#L26-L38
    For some reason Fragment here do validation and invoke viewmodel's method `addTask` with passed `name`, `description` params. While it's viewmodel's responsibility to validate and to read current state of inputs. 
 
    2. https://github.com/kotleni/PomodoroProject-android/blob/9204a862e0e650b66ae581e8914d05f8141ac69b/app/src/main/java/kotleni/pomodoro/viewmodels/NewTaskViewModel.kt#L10-L20
    This viewmodel is just a model. Why would you call it a viewmodel?
    
    3. 
    
4. Lifecycle-aware components

    1. https://github.com/kotleni/PomodoroProject-android/blob/a5cdc0c3741a5d895eac781322f4dee298e647a2/app/src/main/java/kotleni/pomodoro/fragments/TasksFragment.kt#L32
    This is a forbidden usecase for fragment, because on configuration change the listener will be null since Android is free to recreate your fragment whenever it wants to. So all the state basically should be stored in Bundles. And if you want to pass events you should consider to use [fragment result api](https://developer.android.com/guide/fragments/communicate)

5. Getter functions in Kotlin

    https://github.com/kotleni/PomodoroProject-android/blob/9204a862e0e650b66ae581e8914d05f8141ac69b/app/src/main/java/kotleni/pomodoro/viewmodels/TasksViewModel.kt#L17

    In Kotlin you should you properties instead of getters. Such a code is not the best practice.
    
6. Context switching in ViewModel

    https://github.com/kotleni/PomodoroProject-android/blob/9204a862e0e650b66ae581e8914d05f8141ac69b/app/src/main/java/kotleni/pomodoro/viewmodels/TasksViewModel.kt#L21-L27
    
    Repository should switch context instead. But if you use ktor then the library will do it for you.

7. https://github.com/kotleni/PomodoroProject-android/blob/9204a862e0e650b66ae581e8914d05f8141ac69b/app/src/main/java/kotleni/pomodoro/utils.kt#L15 

    1. Consider to use KClass here
    
    2. It's better not to suppose that all viewmodels will have the same params, but you can add a lambda for creating viewModel
    
    ```kotlin
    inline fun <reified T : ViewModel> ViewModelStoreOwner.createViewModel(
        context: Context,
        builder: (...) -> T
    ): T {
        val instance = builder(...)
        ...
    }
    ```
    
8. Eliminate RepositotiesContainer. You can just use an object for manual DI or some DI-library instead.

9. https://github.com/kotleni/PomodoroProject-android/blob/9204a862e0e650b66ae581e8914d05f8141ac69b/app/src/main/java/kotleni/pomodoro/repos/TasksRepository.kt#L9-L20
    Room supports suspend operations, don't use blocking variants here since you may forgot that they are not supposed to be called from non-blocking context.

**Comment by kotleni** [comment]
**Thanks for code review.**

1. OK.
2. It's just a callbacks setters. Keyword `this` needed beacause function parameters have same names.
3. <br>
    I. Do I need to implement all validations in the view model?<br>
    II. Perhaps in the future it will have logic related to View. Should such models be called "models"? (without View*)<br>
    III. ?
4. OK
5. OK
6. OK
7. <br>
    I. OK<br>
    II. OK. It's great idea.
8. OK
9. OK

I need some time for fixing this issues. :)

**Comment by y9vad9** [comment]
> 3. I. Do I need to implement all validations in the view model?
>     II. Perhaps in the future it will have logic related to View. Should such models be called "models"? (without View*)

Yes, you can, but the problem is that view model is logically about providing a state and nothing more. So, use-case or something like that (model means that there is some source of data & truth. So it can be anything, you shouldn't name it model)

**Comment by kotleni** [comment]
> > 3. I. Do I need to implement all validations in the view model?
> >    II. Perhaps in the future it will have logic related to View. Should such models be called "models"? (without View*)
> 
> Yes, you can, but the problem is that view model is logically about providing a state and nothing more. So, use-case or something like that (model means that there is some source of data & truth. So it can be anything, you shouldn't name it model)

By data source, do you mean LiveData? Otherwise I don't need to inherit from ViewModel?

**Comment by y9vad9** [comment]
> > > 3. I. Do I need to implement all validations in the view model?
> > >    II. Perhaps in the future it will have logic related to View. Should such models be called "models"? (without View*)
> > 
> > 
> > Yes, you can, but the problem is that view model is logically about providing a state and nothing more. So, use-case or something like that (model means that there is some source of data & truth. So it can be anything, you shouldn't name it model)
> 
> By data source, do you mean LiveData? Otherwise I don't need to inherit from ViewModel?

By data source I mean database, rest api, etc. You still need view model to provide state (for example, list of tasks). ViewModel just asks model (it's not a name of the class or just class, it can be whether set of classes or not) that encapsulates the app's business logic and data (and it's usually a set of classes like data-source, repository, use-case).

**Comment by kotleni** [comment]
Done.
